consumptions/urls.py
from django.urls import include, path
from rest_framework import routers
import consumptions.views


router = routers.DefaultRouter()
router.register('consumptions-api', consumptions.views.ConsumptionViewSet)

app_name = 'consumptions'

urlpatterns = [
    path('', include(router.urls)),
    path('home/', consumptions.views.Index.as_view(), name='index'),
    path('consumption-list/', consumptions.views.ConsumptionList.as_view(), name='consumption_list'),
    path('consumption/create/', consumptions.views.ConsumptionCreate.as_view(), name='consumption_create'),
    path('consumption/<int:pk>/update/', consumptions.views.ConsumptionUpdate.as_view(), name='consumption_update'),
    path('consumption/<int:pk>/delete/', consumptions.views.ConsumptionDelete.as_view(), name='consumption_delete'),
    path('upload/product-categories-csv/', consumptions.views.upload_csv, name='upload_csv'),
    path('upload/product-csv/', consumptions.views.upload_product_csv, name='upload_product_csv'),
]

djangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('consumptions.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

consumptions/models.py
from django.db import models

# Create your models here.


class Product_Category(models.Model):
    code = models.CharField(max_length=200, unique=True)
    name = models.CharField(max_length=200)

    class Meta:
        # Gives the proper plural name for admin
        verbose_name_plural = "Product_Categories"

    def __str__(self):
        return self.code


class Product(models.Model):
    code = models.CharField(max_length=200, unique=True)
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Product_Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.code


class Consumption(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

consumptions/views.py
from django.shortcuts import render

from consumptions.models import Product, Product_Category, Consumption
from consumptions.serializers import ConsumptionSerializer
from consumptions.filters import ConsumptionFilter

from rest_framework import viewsets

from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django_filters.views import FilterView


class ConsumptionViewSet(viewsets.ModelViewSet):
    """Consumption REST API ViewSet, includes Create, Update, Delete"""
    queryset = Consumption.objects.all()
    serializer_class = ConsumptionSerializer


class Index(View):
    template_name = 'index.html'

    def get(self, request):
        return render(request, self.template_name)


class ConsumptionList(FilterView):
    """Consumption list with option to filter by product category"""
    model = Consumption
    context_object_name = 'consumptions'
    template_name = 'consumption_list.html'
    filterset_class = ConsumptionFilter


class ConsumptionCreate(CreateView):
    model = Consumption
    fields = ['product', 'quantity']
    template_name = 'consumption_form.html'
    success_url = reverse_lazy('consumptions:consumption_list')


class ConsumptionUpdate(UpdateView):
    model = Consumption
    fields = '__all__'
    template_name = 'consumption_form.html'
    success_url = reverse_lazy('consumptions:consumption_list')


class ConsumptionDelete(DeleteView):
    model = Consumption
    template_name = 'consumption_confirm_delete.html'
    success_url = reverse_lazy('consumptions:consumption_list')


def upload_csv(request):
    db_codes = {}
    p_list = Product_Category.objects.all().values_list('code')
    for i in range(0, len(p_list)):
        db_codes[p_list[i][0]] = p_list[i][0]

    if request.method == "POST":
        csv_file = request.FILES["csv_file"]

        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'This is not a csv file')
        else:
            file_data = csv_file.read().decode("utf-8")
            lines = file_data.split("\n")
            for line in lines[1:]:
                fields = line.split(",")
                if len(fields) == 2:
                    print(fields)
                    code = fields[0]
                    name = fields[1]
                    if code not in db_codes:
                        Product_Category(code=code, name=name).save()
            messages.success(request, 'Form submission successful')
    return render(request, "upload_csv.html")


def upload_product_csv(request):
    db_codes = {}
    p_list = Product.objects.all().values_list('code')
    for i in range(0, len(p_list)):
        db_codes[p_list[i][0]] = p_list[i][0]

    if request.method == "POST":
        csv_file = request.FILES["csv_file"]

        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'This is not a csv file')
        else:
            file_data = csv_file.read().decode("utf-8")
            lines = file_data.split("\n")
            for line in lines[1:]:
                fields = line.split(",")
                if len(fields) == 3:
                    code = fields[0]
                    name = fields[1]
                    category = fields[2]
                    category = Product_Category.objects.get(code=category)
                    # if category not in Product_Category.objects.all():
                    if fields[0] not in db_codes:
                        Product(code=code, name=name, category=category).save()
            messages.success(request, 'Form submission successful')
    return render(request, "upload_product_csv.html")

consumptions/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Consumptions Manager</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'consumptions:index' %}">Home</a></li>
          <li><a href="{% url 'consumptions:consumption_list' %}">Consumptions</a></li>
          <li><a href="{% url 'consumptions:upload_csv' %}">Upload Product Categories Resourses</a></li>
          <li><a href="{% url 'consumptions:upload_product_csv' %}">Upload Product Resourses</a></li>
        </ul>
        {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

consumptions/templates/consumption_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Consumption</h1>

<p>Are you sure you want to delete the product consumption: {{ consumption.product }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

consumptions/templates/consumption_form.html
{% extends "base.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

consumptions/templates/consumption_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-10">
      <h1>Consumption Data Table</h1>
      <div class="buttons">
        <div><a role="button" class="btn btn-primary btn-create" href="{% url 'consumptions:consumption_create' %}">Create new</a>
        </div>
        <div class="filter">
          <form method="get">
            {{ filter.form }}
            <button class="btn btn-primary" type="submit">Filter by product category</button>
          </form>
        </div>
      </div>
      <table class="table">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Product</th>
          <th scope="col">Quantity</th>
        </tr>
        {% for consumption in consumptions %}
        <tr>
          <td>{{ consumption.id }}</td>
          <td>{{ consumption.product }}</td>
          <td>{{ consumption.quantity }}</td>
          <td><a role="button" href="{% url 'consumptions:consumption_update' consumption.id %}">Edit</a></td>
          <td><a role="button" href="{% url 'consumptions:consumption_delete' consumption.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </div>
  </div>
</div>


{% endblock %}

consumptions/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-10">
      <h1>Consumptions Manager</h1>
      <p>Welcome to Telecom Service Consumptions Manager!</p>
    </div>
  </div>
</div>
{% endblock %}

consumptions/templates/upload_csv.html
{% extends "base.html" %}

{% block content %}

<form action="{% url 'consumptions:upload_csv' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Upload Product Categories CSV</h3>
    <div class="file-div">
        <label for="name">File:</label>
        <input type="file" name="csv_file" required="True">
    </div>
    <div>
        <div class="p-3">
            <button class="btn btn-primary">Upload</button>
        </div>
    </div>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}


{% endblock %}

consumptions/templates/upload_product_csv.html
{% extends "base.html" %}

{% block content %}

<form action="{% url 'consumptions:upload_product_csv' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Upload Products CSV</h3>
    <div class="file-div">
        <label for="name">File:</label>
        <input type="file" name="csv_file" required="True">
    </div>
    <div>
        <div class="p-3">
            <button class="btn btn-primary">Upload</button>
        </div>
    </div>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}


{% endblock %}